### ISSUE TITLE
Spring-mybatis 整合的比较好，有没有想继续扩展下

### ISSUE THREAD

**Issue by abshawn** [MatrixSeven/Spring-mybatis#1]
加上spring security，以及前台的一些技术 实现用户的管理

**Comment by MatrixSeven** [comment]
其实这个框架当初是给一个实习生(其实我也才毕业哈哈哈。。。)搭建的，后续已经集成了Shiro和Lucene。
但是我不介意咱们一起完善您说的  “加上spring security，以及前台的一些技术 实现用户的管理”内容。
如果您有兴趣，请发送邮件到hacker.kill07@gmail.com
